- src/components/Paper/PaperBox.jsx
- src/components/Paper/PaperBox.style.js
- 하나만 export 할 때 default로 해야하는 설정 때문에 에러 발생
- default로 export 해서 해결
- PaperBox.style.js 의 export 부분 수정
> Fix : export 오류 해결

- src/pages/SendMessage.jsx
- 컴포넌트 경로 오류 해결
- SendMessage 에서 Header 컴포넌트 import 하는 부분 수정
> Fix : 컴포넌트 경로 오류 수정

- src/components/CreatePaper/BackgroundBox.jsx
- src/components/CreatePaper/BackgroundSelector.jsx
- src/components/CreatePaper/BackgroundText.jsx
- src/components/CreatePaper/ColorImgSelector.jsx
- src/components/CreatePaper/CreateButton.jsx
- src/components/CreatePaper/CreatePaper.jsx
- src/components/CreatePaper/FormContainer.jsx
- src/components/CreatePaper/RecipientInput.jsx
- src/components/Header/Header.jsx
- src/components/Header/Logo.jsx
> [Fix] 대소문자 구분 옵션 켜고 변경사항 업로드

- src/apis/getApi.js
- src/components/Paper/Button/ArrowButton.style.js
- src/components/Paper/Button/LeftArrowButton.jsx
- src/components/Paper/Button/RightArrowButton.jsx
- src/components/Paper/PaperContainer.jsx
- src/components/Paper/PaperContainer.style.js
- src/constants/paperConstants.js
- src/hooks/useFetchData.js
- src/utils/getCarouselIndex.js
-  endpoint를 파라미터로 받아서 데이터를 조회 -> 실제데이터를 렌더링
- 커스텀 훅 분리
- fetchData 함수 구현 ( apis/getApi.js )
- endpoint를 파라미터로 받아서 fetchData함수를 이용해 response를 반환하는 useFetchData 커스텀 훅 구현
- 캐러셀 기능의 화살표 너무 복잡한 것 같아 보여서 컴포넌트 분리했습니다.
- 캐러셀 기능을 위해 쓰이는 로직을 유틸함수로 작성해서 분리
- 잘 모르겠습니다... 
- 오타같은거나 컨벤션 어긴것들, 더 좋은 방법이 있을 것 같다 하시는것들 전부 다 마구 알려주십쇼..!!
> [Feat] api 데이터 불러와서 적용하고 커스텀 훅으로 분리

- src/components/CreatePaper/BackgroundBox.jsx
> [Fix] 일부파일 첫줄삭제

- src/apis/recipientApis.js
- src/components/Button/SubmitButton.jsx
- src/components/Button/SubmitButton.style.jsx
- src/components/Text/Editor.jsx
- src/pages/Message/SendMessage.jsx
- SubmitButton 활성화 기능을 구현하였습니다!
- POST api 생성 후 생성한 데이터 업데이트 기능을 구현하였습니다!
- !data.sender || !data.content를 통한 SubmitButton 활성화
- POST api 구현
- useNavigate 통한 경로 이동
- isSuccess 상태 업데이트
- 아직 id값을 넘겨받지 못해서 임의로 '2508'로 id값 넘겨주었습니다! id값 넘겨오는데로 수정하도록 하겠습니다! (현재 SendMessage.jsx 파일에서 usedId를 통해 id값 넘겨받을려했는데 못 받아서 해당 부분들은 추후에 지우고 수정하도록 하겠습니다!)
- 현재 에디터를 통해 입력된 값들이 줄바꿈을 인식하지 못하고 있습니다. 이 부분 빠르게 수정해보도록 하겠습니다.
- 에디터 수정이 빠르게 되면 (오래 걸릴 것 같습니다만...) 반응형 디자인 추가해 보도록 하겠습니다!
> [Func] 롤링페이퍼 메세지 보내기 페이지 : SubmitButton 활성화 및 데이터 보내기

- src/apis/postApis.js
- src/assetes/images/edit-button.svg
- src/components/Card/Card.jsx
- src/components/Card/CardContainer.jsx
- src/components/Card/PostPageHeader.style.js
- src/pages/Post/Post.jsx
- src/pages/Post/Post.stytle.js
- 카드 상태를 버튼을 통해 수정<->불가 상태 전환하고, 수정 가능 상태에서 삭제할 수 있도록 구현하였습니다. 
- 기능함수 위주로 구현하였습니다. 
- 1) url을통해 edit 모드로 전환되는게 아무래도 이상한 ui라고 생각되어 버튼을 통해 구현하였습니다.
- 디자인은 참담합니다. 
- 2) 삭제 후에 랜더링 되는 로직이 기능상은 문제 없으나, 비효율적일 것으로 보입니다. 이 부분 개선의견 부탁드립니다
> [Feat] post page 카드 상태 및 삭제기능 구현

- package-lock.json
- src/components/Button/ToggleButton.jsx
- src/components/Button/ToggleButton.style.jsx
- src/components/Input/InputText.jsx
- src/components/Input/InputText.style.jsx
- src/components/ProfileImages/ProfileImagesOptionList.jsx
- src/components/Text/Editor.jsx
- src/pages/Message/SendMessage.jsx
- 넘어온 페이지에서 recipientId값을 받아 업데이트하고 페이지 전환 기능을 구현하였습니다.
- react-quill 에디터에서 줄바꿈 기능을 구현하였습니다.
- useParmas를 사용하여 id값 추출
- dangerouslySetInnerHTML 사용하여 에디터 줄바꿈 구현
- 롤링페이퍼 메세지 보내기 페이지 기능 구현 완료했습니다!!
- 반응형과 스타일링 부분은 아직 완성되지 않아서 이제 완성시키도록 하겠습니다!
- 코드 분리 등 코드 재사용할 수 있는 부분들도 서서히 수정하도록 하겠습니다!
(인덕님 Card.jsx에서 {content} 불러오는 부분 dangersoulySetInnerHTML 속성 사용하는 걸로 변경하였습니다! 참고 부탁드립니다!)
> [Func] 롤링페이퍼 메세지 보내기 페이지 : recipientId값 받아오기 구현 및 에디터 줄바꿈 구현(모든 기능 완료)

- src/components/Card/Card.jsx
- react-quill 에디터 줄바꿈 기능 누락 수정
> [Func] 에디터 줄바꿈 기능 누락 수정

- src/components/Button/SubmitButton.style.jsx
- src/components/Button/ToggleButton.style.jsx
- src/components/Input/InputText.jsx
- src/components/Input/InputText.style.jsx
- src/components/ProfileImages/ProfileImagesMain.style.jsx
- src/components/Text/Editor.style.jsx
- src/pages/Message/SendMessageForm.style.jsx
- 태블릿, 모바일 반응형 디자인 적용했습니다/
- 롤링페이퍼 메세지 보내기 페이지 작성 완료했습니다!
- 지금 페이지는 완성되었지만 반응형 디자인이랑 스타일링 부분을 약간 때려박은(?) 느낌이라 수정이 필요할 것 같습니다ㅠㅠ 이제 페이지는 완료해서 클린 코드 작성하도록 하겠습니다!
> [Design] 롤링페이퍼 메시지 보내기 페이지 : 반응형 디자인 적용(페이지 완료)

- src/components/Header/Header.jsx
- src/components/Header/Header.style.js
- src/components/Header/Logo.style.js
- src/components/Home/MainBox.style.js
- src/components/Home/MainItemBox.style.js
- src/components/Home/MainTextBox.style.js
- src/pages/Home/Home.style.js
- 모바일 화면 페이지에 따라 내비바 생성 or 숨김
- 코드 컨밴션에 맞게 리팩토링
- 모바일 화면시 '/' 페이지와 '/list' 페이지를 제외한 나머지 페이지에서 내비게이션바 숨김
- px -> rem 변경
- 필요없는 주석 or 중복된 코드 삭제
- 코드 돌려보며 수정할 부분은 다 수정하였는데 혹시 놓친게 있다면 말씀 부탁드립니다!
> [Feat] 모바일 화면 페이지에 따른 내비바 구현 / 리팩토링

- src/pages/List/List.style.js
- src/router/router.jsx
- 넓이 수정
- 넓이 수정 및 router 잘못된 경로에 접속 시 Error 컴포넌트 보이도록
> [Design]전체 넓이 수정 및 잘못된 경로 모두에 Error 페이지 적용

- src/components/CreatePaper/BackgroundSelector.jsx
- src/components/CreatePaper/BackgroundText.jsx
- src/components/CreatePaper/ColorImageSelector.jsx
- src/components/CreatePaper/CreateButton.jsx
- src/components/CreatePaper/CreateButton.style.jsx
- src/components/CreatePaper/FormArea.jsx
- src/components/CreatePaper/RecipientInput.jsx
반응형 디자인 작업전에
스타일 마무리하였습니다.
스타일드컴포넌트 분리는 반응형 작업 끝난후에 할생각입니다.
createbutton 컴포넌트에 비활성화기능을 마무리작업했습니다.
*post로 보내는 백그라운드이미지url이 잘못되어 수정했습니다.
useApiFetch(string, callBack) {
code blah blah~~~~
- 큰변경사항이 없어 간단한 체크만 하셔도될거같아요
> [Design] 스타일 마무리&코드수정

- src/components/CreatePaper/BackgroundText.jsx
- src/components/CreatePaper/ColorImageSelector.jsx
- src/components/CreatePaper/CreateButton.style.jsx
- src/components/CreatePaper/FormArea.jsx
- src/components/CreatePaper/RecipientInput.jsx
- 반응형 디자인 추가함
- 재명님의 input 마우스focus 이벤트 추가
[Screenshot 2024-01-26 at 19 54 55](https://github.com/Dev-Duke-Seo/rolling_team1/assets/37208116/85c4c2a4-a7d0-4ff4-a44b-8c773aee273a)
웨일브라우저의 영상캡처기능을 이용해봤습니다
- 반응형에 좀더 디테일하게 수정할부분이 있는지 궁금해요
> [Design] 반응형 디자인 추가

- src/components/Card/PostPageHeader.jsx
- src/components/Card/PostPageHeader.style.js
- 이모지 리스트 팝업 생성
- PostPageHeader에 이모지 팝업 추가
- 화살표 버튼 클릭 시 이모지 리스트 get 요청
- 받아온 이모지 리스트 팝업 띄우기
- 팝업 이외 다른 곳 클릭 시 팝업 닫힘
- 아직 추가안된 기능 있어서 추가했습니다! PostPageHeader는 인덕님 작업 영역이랑 겹칠까봐 아직 컴포넌트 분리 거의 안한 상태라 감안하고 봐주세요!
> [Feat] 이모지 리스트 전체(최대 9개) 숨기기/보이기 기능 추가

- src/components/Button/SubmitButton.style.js
- src/components/Button/ToggleButton.style.js
- src/components/Input/InputText.style.js
- src/components/ProfileImages/ProfileImagesMain.jsx
- src/components/ProfileImages/ProfileImagesMain.style.js
- src/components/ProfileImages/ProfileImagesOptionList.style.js
- src/components/Text/Editor.style.jsx
- src/pages/Message/SendMessage.jsx
- src/pages/Message/SendMessageForm.style.js
- src/pages/NotFound/NotFound.style.js
- 통일성 유지보수를 위한 스타일링을 재구성하였습니다.
- px -> rem으로 변경(미디어 쿼리 제외)
- 확장자 변경
- 속성 순서 재배치
- 미디어 쿼리에서 태블릿과 모바일 사이즈 규정하는 px 제외하고는 rem으로 수정하였습니다!
> [Design] 롤링페이퍼 메세지 보내기 페이지 : 통일성 유지를 위한 스타일링 수정

- src/components/Button/ImageButton.jsx
- src/components/Button/ImageButton.style.js
- src/components/Button/ScrollToTopButton.jsx
- src/components/Button/ScrollToTopButton.style.js
- src/components/Card/PopUpButton.jsx
- src/components/Card/PostPageHeader.jsx
- src/components/Common/ImageList.style.js
- src/components/Header/Header.style.js
- 무한 스크롤이 완성됨에 따라 Nav바가 고정되어있지 않으면 불편할 것 같아서 고정했습니다
- 같은 이유로 맨위로 가기 버튼을 추가해봤습니다
- post 페이지 하단에 맨 위로 가기 버튼 컴포넌트 생성
- Nav바 스타일 속성 변경
- 리팩토링도 추후 더 해보면 좋을 것 같습니다~~
> [Feat] 스크롤 Top 버튼 생성 및 스타일 변경

- src/pages/Message/SendMessage.jsx
- src/pages/Post/Post.jsx
> [Refcator] 주석 제거 및 공백 제거

- src/components/ProfileImages/ProfileImagesMain.style.js
- src/components/ProfileImages/ProfileImagesOptionList.style.js
- src/components/Text/Editor.jsx
- src/components/Text/Editor.style.js
- 불필요한 스타일 제거 및 효과 추가했습니다.
- 에디터 border 제거
- 프로필 이미지 리스트 효과 추가
- 주석 제거
- 수정 사항 변경했습니다!
> [Refactor] 스타일 수정

- src/components/Card/Card.jsx
- src/components/Header/Header.style.js
- src/components/Modal/CardModal.style.js
- src/components/Paper/Button/ArrowButton.style.js
- src/components/Paper/Paper.jsx
- src/components/Paper/Paper.style.js
- src/pages/Post/Post.jsx
- 코드 리팩토링 및 화면 버그 수정
- 캐러셀의 화살표 버튼이 nav바와 겹치는 문제가 있어서 수정했습니다.
- nav바의 z-index를 조정하면서 modal의 dim배경 z-index도 함께 수정했습니다
- 하면서 scroll 막기도 있으면 좋은 기능이라 추가했습니다
- rem으로 바꾸는 과정에서 오타가 발생하신 것 같던데 그 부분 수정했습니다
- 또 카드 제목부분은 눌러도 모달이 안나와서 보니 컨텐츠에만 클릭이벤트가 있어서 카드 전체로 옮겼습니다. 인덕님 확인 부탁드려요
- 다른 분들이 작성하신 코드를 수정한 부분이 있어서 확인 부탁드립니다! 밤이라 일단 수정 먼저하게 됐는데 잘 동작하긴하나 의도한 바와 다르다면 말씀해주세요!!
> [Refactor] 화면 버그 수정 & 코드 오타 수정

- src/pages/Message/SendMessage.jsx
********** [GIT] DEPLOY MERGE **********
> ********** [GIT] DEPLOY MERGE ********** 

- README.md
- src/components/CreatePaper/RecipientInput.style.js
> [Fix] Eslint 오류 수정 및 README 수정

- src/components/Header/Header.jsx
- src/components/Header/Header.style.js
- 특정 페이지에서 내비게이션바 숨김 기능 수정하였습니다.
- 기존 영역은 그대로인 상태에서 내비게이션바가 숨김처리 되었는데, 영역 자체를 숨김 처리 하는 것으로 수정하였습니다.
(변경 전)
(변경 후)
> Feat: 내비게이션바 특정 페이지에서 영역 숨김

- README.md
- 마크다운 문법으로 작성하면 이미지 크기조절이 안돼서 html 로 다시 작성해서 내용도 조금 수정했습니다
- readme말고 바뀐 것 없습니다!
> [Refactor] README.md 수정
